### ISSUE TITLE
Blue Home

### ISSUE THREAD

**Issue by coserotondo** [Flo-Schilli/ha-grohe_smarthome#6]
Just installed. Thank you for your work !

I've Blue Home and could be useful to add the `filter_type `sensor:

`device_class: ENUM`
S_SIZE(1), ACTIVE_CARBON(2), ULTRA_SAFE(3), MAGNESIUM_PLUS(4), M_SIZE(5)

Some cosmetics feedback:

I've the CO2 remaining percentage mapped as a battery:
![image](https://github.com/user-attachments/assets/76719cbd-ecac-454a-9b2d-fa62ba9bbf69)

The CO2 and Filter percentages have "battery" type icons:
![image](https://github.com/user-attachments/assets/e1dc3cd8-ae84-43bc-b654-ec3cac113950)

**Comment by Flo-Schilli** [comment]
Hi @coserotondo :wave: 

thanks for opening the issue :blush: 

For the cosmetic feedback: The filters (as they are in percentage) I just implemented them as battery, but I'll check for a different sensor which is matching. This then also means that it is not listed in any 'battery' related views, which can be used for monitoring 'batteries'. For instance I'm using this card to monitor all kinda stuff I have to replace/fill regularly: https://github.com/maxwroc/battery-state-card

With the filter_type sensor. It's not going to be a problem to add them, but I would really appreciate it if you could run this action in "Developer Tools -> Actions": "Grohe Smarthome: Get Appliance details" and select your Grohe Blue. This makes it easy for me to get the path and add the sensor.

/Schilli

**Comment by coserotondo** [comment]
Thank you for explaining and taking care of this.

` filter_type ` is under the ` params ` key:

```
params:
  water_hardness: 0
  carbon_hardness: 20
  filter_type: 5
  variant: 4
  auto_flush_reminder_notif: false
  consumables_low_notif: true
  product_information_notif: true
```
